import { test, expect, Page } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'

async function accessible(page: Page) {
  const report = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa', 'wcag22aa']).analyze()
  expect(report.violations, JSON.stringify(report.violations.map(v => ({ id: v.id, nodes: v.nodes.map(n => n.target) })))).toEqual([])
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
}

async function capture(page: Page, path: string) {
  // Capture from scroll origin: Chromium otherwise composites off-screen fixed
  // skip links into full-page images at the previous scroll offset.
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path, fullPage: true })
}

test('VAL-001/002/006/007/009/011/014/029/030/033/034/043/054/055 search → card → source → feedback', async ({ page }, testInfo) => {
  await page.goto('/')
  await expect(page.getByRole('heading', { name: /มีความหมายในใจ/ })).toBeVisible()
  await accessible(page)
  await capture(page, testInfo.outputPath('home.png'))
  await page.getByRole('button', { name: 'ค้นหาคำ', exact: false }).first().click()
  await expect(page.getByRole('alert')).toContainText('ลองพิมพ์คำ')
  await page.getByLabel('คำ ความหมาย หรือสิ่งที่คุณอยากสื่อ').fill('  อนุรักษ์  ')
  await page.getByRole('button', { name: 'ค้นหาคำ', exact: false }).first().click()
  await expect(page.locator('.candidate').first()).toContainText('อนุรักษ์')
  await expect(page.locator('.candidate').first()).toContainText('ตรงกับคำค้น')
  await accessible(page)
  await page.locator('.candidate').first().getByRole('link').focus()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('heading', { name: 'อนุรักษ์', exact: true })).toBeVisible()
  await expect(page.getByTestId('source-content')).toContainText('รักษาให้คงเดิม')
  await page.getByRole('button', { name: /Thai Wiktionary/ }).first().click()
  await expect(page.getByRole('dialog')).toContainText('CC-BY-SA-4.0')
  await accessible(page)
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).not.toBeVisible()
  await page.getByRole('button', { name: /ช่วยอธิบายคำนี้/ }).click()
  await expect(page.locator('.claims')).toContainText('รักษาให้คงเดิม')
  await page.getByRole('button', { name: /ดูหลักฐาน/ }).first().click()
  await expect(page.getByRole('dialog')).toContainText('รักษาให้คงเดิม')
  await page.keyboard.press('Escape')
  const feedback = page.locator('article .feedback').first()
  await feedback.getByRole('button', { name: 'มีประโยชน์', exact: true }).click()
  await expect(feedback.getByRole('status')).toContainText('บันทึกความคิดเห็นแล้ว')
  await feedback.getByRole('button', { name: 'ยังไม่ตรงใจ' }).click()
  await expect(feedback.getByRole('button', { name: 'ยังไม่ตรงใจ' })).toHaveAttribute('aria-pressed', 'true')
  await feedback.getByText('แจ้งปัญหาข้อมูล', { exact: true }).click()
  await feedback.getByRole('button', { name: 'ส่งรายงาน' }).click()
  await expect(feedback.getByRole('status')).toContainText('รับแจ้งปัญหาแล้ว')
  await accessible(page)
  expect(await page.locator('.skip-link').evaluate(el => el.getBoundingClientRect().bottom)).toBeLessThanOrEqual(0)
  await capture(page, testInfo.outputPath('word-card.png'))
  await page.getByRole('link', { name: '← กลับไปผลการค้นหา' }).click()
  await expect(page.locator('.candidate').first()).toContainText('อนุรักษ์')
  await expect(page.getByLabel('คำ ความหมาย หรือสิ่งที่คุณอยากสื่อ')).toHaveValue('  อนุรักษ์  ')
})

test('VAL-015/016/017/018 comparison source panels and invalid selections', async ({ page }, testInfo) => {
  await page.goto('/#/compare')
  const compare = page.getByRole('button', { name: /เปรียบเทียบสองคำ/ })
  await expect(compare).toBeDisabled()
  await page.getByLabel('คำที่ต้องการเปรียบเทียบ').fill('อนุรักษ์')
  await page.getByRole('button', { name: /เพิ่มคำ/ }).click()
  await expect(page.locator('.selected-words')).toContainText('อนุรักษ์')
  await page.getByLabel('คำที่ต้องการเปรียบเทียบ').fill('อนุรักษ์')
  await page.getByRole('button', { name: /เพิ่มคำ/ }).click()
  await expect(page.getByRole('alert')).toContainText('เลือกคำนี้แล้ว')
  await page.getByLabel('คำที่ต้องการเปรียบเทียบ').fill('สงวน')
  await page.getByRole('button', { name: /เพิ่มคำ/ }).click()
  await expect(compare).toBeEnabled()
  await compare.click()
  await expect(page.locator('.comparison-grid article')).toHaveCount(2)
  await expect(page.locator('.comparison-grid')).toContainText('ถนอมรักษาไว้')
  await page.getByRole('button', { name: /ช่วยอธิบายคำนี้/ }).click()
  await expect(page.locator('.claims')).toContainText('อนุรักษ์')
  await expect(page.locator('.claims')).toContainText('สงวน')
  await accessible(page)
  await capture(page, testInfo.outputPath('comparison.png'))
})

test('VAL-019/020/021/022 context selectable spans and ambiguity', async ({ page }, testInfo) => {
  await page.goto('/#/context')
  await page.getByLabel('ประโยคหรือข้อความภาษาไทย').fill('เราช่วยกันอนุรักษ์ภาษาไทย')
  await page.getByRole('button', { name: /อ่านคำในข้อความ/ }).click()
  await page.getByRole('button', { name: /เลือกคำว่า อนุรักษ์/ }).focus()
  await page.keyboard.press('Enter')
  await expect(page.locator('.context-word')).toContainText('รักษาให้คงเดิม')
  await expect(page.locator('.claims')).toContainText('อนุรักษ์')
  await accessible(page)
  await capture(page, testInfo.outputPath('context.png'))
  await page.getByLabel('ประโยคหรือข้อความภาษาไทย').fill('ขัน')
  await page.getByRole('button', { name: /อ่านคำในข้อความ/ }).click()
  await page.getByRole('button', { name: /เลือกคำว่า ขัน/ }).click()
  await expect(page.locator('.context-word')).toContainText('หลายความหมายที่อาจเป็นไปได้')
})

test('VAL-008/032/047/049/059 empty, model failure, stale and privacy', async ({ page }) => {
  await page.goto('/#/word/%E0%A4%A')
  await expect(page.getByRole('alert')).toContainText('ไม่พบคำนี้')
  await page.goto('/')
  await page.getByRole('link', { name: 'ข้ามไปเนื้อหาหลัก' }).focus()
  await page.keyboard.press('Enter')
  await expect(page.locator('main')).toBeFocused()
  expect(new URL(page.url()).hash).not.toBe('#main')
  await page.getByLabel('คำ ความหมาย หรือสิ่งที่คุณอยากสื่อ').fill('zzzzzqqqqqxxxx')
  await page.getByRole('button', { name: 'ค้นหาคำ', exact: false }).first().click()
  await expect(page.locator('.empty-state')).toContainText('ยังไม่พบคำที่มั่นใจได้')
  await page.goto('/#/word/w_stale')
  await expect(page.getByRole('alert')).toContainText('ไม่พบคำนี้')
  await page.goto('/#/word/' + encodeURIComponent('อนุรักษ์'))
  await expect(page.getByTestId('source-content')).toBeVisible()
  await page.route('**/api/explanations', route => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ data: null, meta: { correlation_id: 'test' }, error: { code: 'UNAVAILABLE', message: 'คำอธิบายไม่พร้อม กรุณาลองอีกครั้ง' } }) }))
  await page.getByRole('button', { name: /ช่วยอธิบายคำนี้/ }).click()
  await expect(page.getByRole('alert')).toContainText('คำอธิบายไม่พร้อม')
  await expect(page.getByTestId('source-content')).toContainText('รักษาให้คงเดิม')
  await page.getByRole('button', { name: 'ข้อมูลและความเป็นส่วนตัว' }).click()
  await expect(page.getByRole('dialog')).toContainText('ไม่มีคุกกี้ติดตาม')
  await accessible(page)
})

test('VAL-023/024/025/026/038 map and list have the same sourced edges', async ({ page, request }) => {
  const response = await request.get('/api/words/' + encodeURIComponent('ศูนย์') + '/related')
  // Use a real explicit cross-reference if present in the corpus; otherwise inspect real sparse behavior.
  const map = response.ok() ? (await response.json()).data : null
  await page.goto('/#/word/' + encodeURIComponent('ศูนย์'))
  if (map?.relationships.length) {
    await expect(page.locator('.relation-list li')).toHaveCount(map.relationships.length)
    await expect(page.getByRole('img', { name: /แผนที่คำ/ })).toBeVisible()
    await accessible(page)
    await page.locator('.relation-list li').first().getByRole('link').click()
    await expect(page.getByRole('heading', { name: map.relationships[0].word, exact: true })).toBeVisible()
  } else {
    await page.goto('/#/word/' + encodeURIComponent('อนุรักษ์'))
    await expect(page.locator('.empty-map')).toContainText('ยังไม่มีข้อมูลคำที่เกี่ยวข้อง')
    await accessible(page)
  }
})
